### ISSUE TITLE
Update library for it to be python3 compatible

### ISSUE THREAD

**Issue by breadplop** [mixpanel/mixpanel-utils#12]

**Comment by thomasf** [comment]
yeah, this is really bad :)

**Comment by aavnsh** [comment]
I've ported the library to python3 which you can install from pip `pip install mixpanel-api3`
[Github: mixpanel_api3](https://github.com/aavnsh/mixpanel_api3)
[PyPi: mixpanel-api3](https://pypi.org/project/mixpanel-api3/)

Hope it helps till the current library is upgraded.

**Comment by paulvelthuisgyg** [comment]
Is there a version of mixpanel for python 3 coming?
Python 2 will not be maintained anymore at the end of this year

**Comment by rverma-nikiai** [comment]
@jaredmixpanel Can you please address this, this has been due from quite some time.

**Comment by pritesh2312** [comment]
@jaredmixpanel @andyleap @tdumitrescu @ttrefren @Uduchi2nd @zakj 
Any updated for support of Python 3 ?

**Comment by danakock** [comment]
Sorry for the delay! This library is written and maintained by the Mixpanel Support Engineering team, and thus, we don't have as much time to work on these projects.  We're in the process of re-writing the library to be fully Python3 compatible though, and the updated version will be released in Q2. 

Until then, I can help with converting any existing code to Python 3.

**Comment by bookmebus** [comment]
@danakock any update on this?

**Comment by colelloa** [comment]
python2 is being EOLed on Dec 31 2019 and will no longer receive security updates - https://pythonclock.org/ - any updates on this?

**Comment by tim-sauchuk** [comment]
Hi everyone!

I've been using the **export_events** function from mixpanel_api3 package for ~6 months now and have noticed that this error shows up every once in a while:
`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

I've also noticed particularly today that export_events has been hanging/running extremely slow (takes about 3 minutes to export something that usually takes 3 seconds). Any insight into this?

**Comment by chingc** [comment]
Dear mixpanel_api,

https://pythonclock.org/

![](https://media1.tenor.com/images/5b8a8ed4fd31635e32e7e68f0ace77ad/tenor.gif?itemid=5304604)

P.S. I'm sorry this comment wasn't helpful.  This library is one of the few that is holding back my company's transition to Python 3.  I have seen [posts](https://community.mixpanel.com/idea/302/make-the-mixpanel-api-compatible-with-python-3.html) going back to the beginning of the year, but have yet to see any status or update.  We are less than 90 days from Python 2 end of life.

**Comment by danakock** [comment]
This has taken longer to update than anticipated due to bandwidth on the team, but we will have this module updated for Python 3 before Python 2 EOL. If anything is holding you back from moving to Python 3 in the meantime, please be aware you can do everything utilizing the APIs documented in our [dev docs](https://developer.mixpanel.com/docs/http) that you can via the module. 

Please write in to support if you have any issues or need any assistance with our APIs. I'll update here once we're ready to release the new module.

**Comment by tim-sauchuk** [comment]
Just an FYI, Mixpanel customer support fixed the bug I had yesterday :)

**Comment by tim-sauchuk** [comment]
Still getting an error on ~10% of **export_events** function calls for mixpanel-api3. Anyone else seeing issues like this?

**Comment by apurvis** [comment]
+1

**Comment by jjk2134** [comment]
+1

**Comment by chingc** [comment]
@tim-sauchuk I wouldn't expect any support for mixpanel-api3 because it's not from the mixpanel team.

> From https://github.com/aavnsh/mixpanel_api3:
>
> This is a python 3 port of the original mixpanel-api (python2) utility by the MixPanel Team. **It was done as a quick weekend hack**

**Comment by chriswhittleston** [comment]
Any update on this @danakock?

**Comment by kendistiller** [comment]
Has anything happened with this? EOL is over and this this thread seemed to have died end of last year.

**Comment by ngnikhilgoyal** [comment]
It's pretty frustrating that in 3 years Mixpanel hasn't bothered to update a library that can't work in py3.

**Comment by chingc** [comment]
I gave up waiting for a python 3 version from the official mixpanel_api team and went with https://github.com/aavnsh/mixpanel_api3

**Comment by jaredmixpanel** [comment]
Apologies for it being so long overdue, but the module is now updated to Python3! It has also been renamed to `mixpanel-utils`. Please see the updated README for details.
