### ISSUE TITLE
Import borken?

### ISSUE THREAD

**Issue by Emixam23** [mixpanel/mixpanel-utils#20]
Hey !

For some reason, the import doesn't show data in mixpanel but I get a `{"status": 1, "error": null}` with curl following [the documentation](https://help.mixpanel.com/hc/en-us/articles/115004734463-Importing-Old-Events).

The example is the following:

```
{
	"event": "$signup",
	"properties": {
		"distinct_id": "481",
		"time": 1321499371,
		"token": "13fe3ddc86eb6f90c4ee7d0d47563150"
	}
}
```

so when I replace the distinct_id, the time (by 1546646400 which is a couple of days ago, we are the 14th, this is the timestamp for the 5th), and the token, I get a new piece of base64 encoded data (encoded from this website https://www.base64encode.org/, I use it from the beginning and everything is working fine).

I send it following [the documentation](https://help.mixpanel.com/hc/en-us/articles/115004734463-Importing-Old-Events) and, nothing appears in Mixpanel. However, it seems that the call works since I get "status 1" in return instead of 0?

Thanks for any help

**Comment by Emixam23** [comment]
The question got closed without any answer, is it normal?

**Comment by jaredmixpanel** [comment]
Issue appears unrelated to the python module code. Please re-open with further detail if issue persists.
