### ISSUE TITLE
Error when opening a file for import

### ISSUE THREAD

**Issue by MatCast** [mixpanel/mixpanel-utils#56]
When using the `import_events` with a JSON file an error is thrown:

`ValueError: invalid mode: 'rbU'`

I think the solution would be to just set the mode to `'rb'` instead.

**Comment by mjahanshahi** [comment]
You can also downgrade your python version to 3.10 which supports `rbU`

**Comment by dongjae93** [comment]
This is fixed in https://github.com/mixpanel/mixpanel-utils/pull/58
